#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
# PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &
# setxkbmap -option "ctrl:nocaps" &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Start the system tray
# tray &

# Start two terminals
# gnome-terminal &
# gnome-terminal &

# Start a browser
# google-chrome &

# Start screensaver
# gnome-screensaver &

# Start sound server
# pulseaudio --start --log-target=syslog &

# gnome-session &
feh --bg-fill https://raw.githubusercontent.com/NixOS/nixos-artwork/5729ab16c6a5793c10a2913b5a1b3f59b91c36ee/ideas/grub-splash/grub-nixos-1.png &
# cd ~/mynotes && gitit &

exec xmonad
